// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkNfC-678C7gEvYPbx3zW7IY3xbHo7kos',
    appId: '1:5799674282:web:01a0011788301860e16bd3',
    messagingSenderId: '5799674282',
    projectId: 'event-management-app-82452',
    authDomain: 'event-management-app-82452.firebaseapp.com',
    storageBucket: 'event-management-app-82452.firebasestorage.app',
    measurementId: 'G-QVYYFX10GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroQu2lqSyKQKdkil4jAua6O_v5-t2r7A',
    appId: '1:5799674282:android:4453d7a79652dee5e16bd3',
    messagingSenderId: '5799674282',
    projectId: 'event-management-app-82452',
    storageBucket: 'event-management-app-82452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_OFDavWU9MBVyV1bmCLda49WXKiQ54qQ',
    appId: '1:5799674282:ios:177c4e7fc25eea15e16bd3',
    messagingSenderId: '5799674282',
    projectId: 'event-management-app-82452',
    storageBucket: 'event-management-app-82452.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_OFDavWU9MBVyV1bmCLda49WXKiQ54qQ',
    appId: '1:5799674282:ios:177c4e7fc25eea15e16bd3',
    messagingSenderId: '5799674282',
    projectId: 'event-management-app-82452',
    storageBucket: 'event-management-app-82452.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkNfC-678C7gEvYPbx3zW7IY3xbHo7kos',
    appId: '1:5799674282:web:ad70f14700df4834e16bd3',
    messagingSenderId: '5799674282',
    projectId: 'event-management-app-82452',
    authDomain: 'event-management-app-82452.firebaseapp.com',
    storageBucket: 'event-management-app-82452.firebasestorage.app',
    measurementId: 'G-5RVS589CV3',
  );
}
